// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"rekeningService/app"
	"rekeningService/controller"
	"rekeningService/repository"
	"rekeningService/service"
)

// Injectors from injector.go:

func InitializedServer() *echo.Echo {
	rekeningRepositoryImpl := repository.NewRekeningRepositoryImpl()
	db := app.GetConnection()
	v := _wireValue
	validate := validator.New(v...)
	rekeningServiceImpl := service.NewRekeningServiceImpl(rekeningRepositoryImpl, db, validate)
	rekeningControllerImpl := controller.NewRekeningControllerImpl(rekeningServiceImpl)
	echoEcho := app.NewRouter(rekeningControllerImpl)
	return echoEcho
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var rekeningSet = wire.NewSet(repository.NewRekeningRepositoryImpl, wire.Bind(new(repository.RekeningRepository), new(*repository.RekeningRepositoryImpl)), service.NewRekeningServiceImpl, wire.Bind(new(service.RekeningService), new(*service.RekeningServiceImpl)), controller.NewRekeningControllerImpl, wire.Bind(new(controller.RekeningController), new(*controller.RekeningControllerImpl)))
